### ISSUE TITLE
Library does not give correct official test vector values

### ISSUE THREAD

**Issue by isaacchua** [hanswolff/curve25519#8]
We found that we couldn't get this and another library that uses Curve25519 to work so we tested both libraries against the official test vectors. In particular, we tested the conversion from the secret key of party A (`d_A`) to the public key (`x_A`). These test vectors are found on the last page of the draft RFC:
https://tools.ietf.org/html/draft-josefsson-tls-curve25519-04

Here is the sample code using the `WallF.BaseNEncodings` package to convert hex to byte arrays:

```
var d_A = "5ac99f33632e5a768de7e81bf854c27c46e3fbf2abbacd29ec4aff517369c660".ToUpper();
var d_A_bytes = BaseEncoding.Base16.FromBaseString(d_A);
var d_A_clamped = Curve25519.ClampPrivateKey(d_A_bytes);

// value should be 057e23ea9f1cbe8a27168f6e696a791de61dd3af7acd4eeacc6e7ba514fda863
var x_A_bytes = Curve25519.GetPublicKey(d_A_bytes); // gives a704c2f860fe0c74c457ed4d0f1b26e907491fa34c3b3af0c2f89bd391f68c01
var x_A_clamped = Curve25519.GetPublicKey(d_A_clamped); // gives 565689ffdf3c5be17b44ab2a5519e28a919b520c2fb9fde9414b46dcdbc99c3b
```

**Comment by isaacchua** [comment]
After much testing, I found that the values given at the draft RFC were least-significant byte first. Hence the byte array had to be reversed before use in this .NET library.

**Comment by hanswolff** [comment]
cool thanks for pointing out what it was
